# Site settings
title: ppenzin
email: 
username: ppenzin
description: "A (possibly technical) blog of Petr Penzin."
baseurl: ""
url: "http://ppenzin.github.io"
r: /static/Penzin.pdf

# Build settings
markdown: kramdown
permalink: pretty

# Set comment provider to 'disqus' or 'facebook' to enable one of those systems
# otherwise comments are disabled. See post template for details.
comments :
  provider : disqus
  disqus :
    shortname: ppenzingithubio
  facebook :
    appid : 666308690117034
    num_posts: 5
    width: 580
    colorscheme: light

static_files:
  resume:
    path: /static/Penzin.pdf
    modified_time: 1441156245
    extname: .pdf
  resume:
    path: /static/hp-pavilion-zv5000-ih3-800.jpg
    modified_time: 1447991246
    extname: .jpg
